service: magic-url-serverless
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements: 
  - Effect: Allow
    Action: 
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:GetItem
      - dynamodb:DeleteItem
    Resource: 'arn:aws:dynamodb:us-east-1:*:*'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  createMagicUrl:
    handler: bin/create_magicurl
    events:
      - http:
          path: magicurl
          method: post
  getMagicUrl:
    handler: bin/get_magicurl
    events:
      - http:
          path: /{slug}
          method: get
          request: 
            parameters: 
               paths: 
                 slug: true
  deleteMagicUrl:
    handler: bin/delete_magicurl
    events:
      - http:
          path: magicurl
          method: delete

resources:
  Resources:
    magicUrlTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: Slug
            AttributeType: S
        KeySchema:
          - AttributeName: Slug
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: magicUrl